name: Pull Request on Github #nome qualquer
on: [pull_request] #tarefa(s) do gitHub
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest #github nos fornecerá a máquina.
    steps:
      - name: Check out repository code #nome qualquer
        uses: actions/checkout@v3 # plugin p/ copiar meu código p/ a máquina do github
      - name: Make a new envfile #nome qualquer
        uses: SpicyPizza/create-envfile@v1.3 # plugin p/ criar um env na máquina do github
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "names"
          envkey_POSTGRES_PORT: 5000
          envkey_DATABASE_URL: "postgresql://postgres:postgres@names:5432/names"
          directory: back-end
          file_name: .env.test
      - name: Run tests #nome qualquer
        run: docker-compose -f docker-compose-test.yml run node npm run test #aqui o "node" é o nome do container